### ISSUE TITLE
Error 500 with sentry 8.6.0 (column auth_user.is_password_expired does not exist)

### ISSUE THREAD

**Issue by sbadia** [getsentry/sentry-auth-google#9]
Just updated my sentry server to the latest `8.6.0` with sentry-auth-google (from master), and I get this traceback.

```python
Traceback (most recent call last):
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/../django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/../django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/../django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/../django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/../django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 175, in dispatch
    return self.handle(request, *args, **kwargs)
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/web/frontend/auth_provider_login.py", line 19, in handle
    return helper.current_step()
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/auth/helper.py", line 160, in current_step
    helper=self,
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/auth/providers/oauth2.py", line 51, in dispatch
    return helper.next_step()
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/auth/helper.py", line 169, in next_step
    return self.current_step()
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/auth/helper.py", line 160, in current_step
    helper=self,
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/auth/providers/oauth2.py", line 129, in dispatch
    return helper.next_step()
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/auth/helper.py", line 169, in next_step
    return self.current_step()
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/auth/helper.py", line 160, in current_step
    helper=self,
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/../sentry_auth_google/views.py", line 65, in dispatch
    return helper.next_step()
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/auth/helper.py", line 169, in next_step
    return self.current_step()
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/auth/helper.py", line 157, in current_step
    return self.finish_pipeline()
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/auth/helper.py", line 178, in finish_pipeline
    response = self._finish_login_pipeline(identity)
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/../django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/auth/helper.py", line 569, in _finish_login_pipeline
    ident=identity['id'],
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/../django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/../django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/../django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/../django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/../django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/../django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/opt/sentry/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 112, in execute
    return real_execute(self, sql, params)
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/../django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/../django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/../django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    raise_the_exception(self.db, e)
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 73, in inner
    return func(self, *args, **kwargs)
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 21, in inner
    return func(self, *args, **kwargs)
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 88, in inner
    return func(self, sql, *args, **kwargs)
  File "/opt/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 39, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: column auth_user.is_password_expired does not exist
LINE 1: ...h_user"."is_superuser", "auth_user"."is_managed", "auth_user...
                                                             ^

SQL: SELECT "sentry_authidentity"."id", "sentry_authidentity"."user_id", "sentry_authidentity"."auth_provider_id", "sentry_authidentity"."ident", "sentry_authidentity"."data", "sentry_authidentity"."last_verified", "sentry_authidentity"."last_synced", "sentry_authidentity"."date_added", "auth_user"."password", "auth_user"."last_login", "auth_user"."id", "auth_user"."username", "auth_user"."first_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."is_superuser", "auth_user"."is_managed", "auth_user"."is_password_expired", "auth_user"."last_password_change", "auth_user"."date_joined" FROM "sentry_authidentity" INNER JOIN "auth_user" ON ( "sentry_authidentity"."user_id" = "auth_user"."id" ) WHERE ("sentry_authidentity"."ident" = %s  AND "sentry_authidentity"."auth_provider_id" = %s )
[ERROR] django.request: Internal Server Error: /auth/sso/ 
```

Thanks in advance,

**Comment by mattrobenolt** [comment]
It looks like you missed a `sentry upgrade`?

**Comment by sbadia** [comment]
:innocent: thanks :)
